package br.edu.unipam.tcc.entity.enums;

public enum ChatState {
    NEW,
    AWAITING_FULL_NAME,
    AWAITING_RA,
    AWAITING_COURSE,
    AWAITING_ACADEMIC_PERIOD,
    MAIN_MENU,
    SETTINGS_MENU,
    SETTINGS_AWAITING_NAME,
    SETTINGS_AWAITING_TIME,
    SETTINGS_AWAITING_COURSE,
    SETTINGS_AWAITING_PERIOD,
    REVIEW_MODE,
    RAG_DOUBT_MODE
}
